metricsbp: Add Timer.OverrideStartTime
reddit/baseplate.go pull request #285
Opened 2020-09-29 17:08 UTC by fishy

2020-09-29 17:11 UTC, pacejackson requested changes
Can you also update https://github.com/reddit/baseplate.go/blob/master/metricsbp/baseplate_hooks.go to use a Timer plus OverrideStartTime rather than a histogram?

2020-09-29 17:30 UTC, fishy commented
> Can you also update https://github.com/reddit/baseplate.go/blob/master/metricsbp/baseplate_hooks.go to use a Timer plus OverrideStartTime rather than a histogram?

Done. Also added `ObserveWithEndTime`.

2020-09-29 17:35 UTC, pacejackson approved these changes
One small suggestion, lgtm otherwise.

2020-09-29 17:35 UTC, pacejackson commented on metricsbp/baseplate_hooks.go
> +		h.timer.OverrideStartTime(time.Now())
```suggestion
		h.timer.Start()
```

2020-09-30 16:06 UTC, konradreiche approved these changes

2020-09-30 16:08 UTC, merged