thriftbp: Add doc regarding the concurrency of ClientPool
reddit/baseplate.go pull request #359
Opened 2021-04-06 17:32 UTC by fishy

It could be confusing on whether the client created from ClientPool is
concurrent safe, and that could lead to footguns, so adding some doc to
explicitly call it out.

2021-04-06 17:33 UTC, konradreiche approved these changes

2021-04-07 15:21 UTC, pacejackson approved these changes

2021-04-07 15:40 UTC, pacejackson requested changes
So it seems like this is actually a regression due to a change in Thrift that caused these clients to become silently non-concurrent safe and I think we should either try to address the regression or there are more things that need to be changed.

The baseplate client pool was meant to make it so you _could_ use the same client, that's why it pulls a new TClient from the pool for you before each call and puts it back.

2021-04-07 15:41 UTC, pacejackson commented
Note, I would prefer if we could address the regression itself as it is not intuitive that you need to new create a new client before each request and makes the API much more cumbersome than it was before.

2021-04-07 16:41 UTC, fishy commented
As discussed offline, to address the regression we would need to introduce a breaking change, so that will be done later, and this change is just the short term doc update.

2021-04-07 16:43 UTC, pacejackson approved these changes

2021-04-07 16:46 UTC, konradreiche approved these changes

2021-04-07 20:52 UTC, merged