Deprecate runtimebp.numProcesses yaml config
reddit/baseplate.go pull request #443
Opened 2021-11-15 17:06 UTC by fishy

We saw some services confused on what it does, and just set the min
number to some large number and hope that will give them better
concurrency performance.

Since we already don't allow services to customize the formula from yaml
config, it really doesn't make much sense to allow them to customize
min/max from the yaml. Deprecate them and remove them in a future
breaking change.

If a service really need a different GOMAXPROCS from number of
container-aware CPUs, they can call runtime.GOMAXPROCS or
runtimebp.GOMAXPROCS after baseplate.New.

Also improve the log from runtimebp.InitFromConfig.

2021-11-15 17:06 UTC, pacejackson approved these changes

2021-11-15 17:08 UTC, konradreiche approved these changes

2021-11-15 22:01 UTC, kylelemons requested changes
Is it possible for this to break anyone?

2021-11-15 22:04 UTC, fishy commented
> Is it possible for this to break anyone?

that depends on how to define "break".

if someone was using

```yaml
runtime:
  numProcesses:
    min: 48
```

to get GOMAXPROCS to 48, this change will revert them back to num cpu rounding up (likely a small number ~2), and it will have performance impacts.

it's... grey area?

2021-11-15 22:06 UTC, fishy commented
searching for "numProcesses file:yaml" in internal sourcegraph only found 2 results, none with `min` set. not sure how much you trust sourcegraph's search :) (the one case I know someone uses  `min: 48` I think they already fixed it).

2022-06-08 16:23 UTC, fishy commented
💇 I believe now is the time to revisit this.

I believe previously the only use case of setting those are setting the min to a large number to essentially "pin" GOMAXPROCS to the same large number, which should no longer be needed after 7895979 & 6ddacb1, as when there's no cpu limit set we just fallback to physical number of cpus instead of cpu request. (cc @konradreiche as your team seems to be the only team doing that)

2022-06-08 16:25 UTC, pacejackson approved these changes

2022-06-08 18:51 UTC, konradreiche approved these changes
We're fine with this since we only set it to get the same behavior that will happen by default with this change :+1:

2022-06-08 19:27 UTC, merged