Add Prometheus metrics to http, grpc, and thrift.
reddit/baseplate.go pull request #467
Opened 2022-01-10 22:21 UTC by JessicaGreben

This PR adds the Prometheus branch to master which contains all default Prometheus metrics for HTTP, GRPC, and Thrift client and servers based on the [baseplate.spec](https://github.snooguts.net/reddit/baseplate.spec/blob/master/component-apis/prom-metrics.md#http).

Background:
All Prometheus metrics changes will be merged in the prometheus branch. We are adding this prometheus branch because if we cut a point release and the master branch only has partial support for Prometheus metrics it could leave some upgraded repos in a confusing state where they have some metrics and not others. Additionally the prometheus metrics changes are too big for a single PR. So the compromise is to merge all incremental Prometheus metrics into this new branch, then once complete we can merge into the master branch.

The expected work that will need to be merged into this prometheus branch is:

- PR for thrift server metric with some testing helpers (PR #433).
- another PR for adding thrift client metrics (PR #442 )
- another PR that adds spec-validation tests (PR #445)
- PR that adds grpc client and server prometheus metrics (PR #447)
- (this PR) a PR that adds http client and server prometheus metrics (PR #451)

2022-01-10 22:33 UTC, kylelemons requested changes
Definitely interested in getting this into preference-go and seeing what it says!

2022-01-10 22:33 UTC, kylelemons commented on grpcbp/client_middlewares.go
> +		serviceName, m := serviceAndMethodSlug(method)
sorry for missing this; I don't really like one-letter variable names unless I could tell you what it meant with no context (i, w, r, etc.)... so maybe name this "method" and call method "serviceMethod" or "wireMethod"?

2022-01-10 22:33 UTC, kylelemons commented on grpcbp/client_middlewares.go
> +		cc *grpc.ClientConn,
conn or clientConn?

2022-01-10 22:33 UTC, kylelemons commented on grpcbp/server_middlewares_test.go
> +			defer promtest.NewPrometheusMetricTest(t, "server rpc count", serverRPCRequestCounter, serverTotalRequestLabels).CheckDelta(1)
Some of these are named almost identically, e.g. "clientActiveRequests" <-> "clientActiveRequestLabels" -- maybe the rest should be unified too?  This (RPC vs Total) stands out the most

2022-01-11 00:46 UTC, konradreiche approved these changes

2022-01-11 23:58 UTC, kylelemons approved these changes

2022-01-12 00:04 UTC, fishy approved these changes
Since we added fixup commits to this branch, we can no longer _just_ rebase merge this PR (which will make the fixup commits land on master branch).

Do we want to squash everything into a single commit? Or if we still want individual commits to be rebased onto master branch in the end, then we need to figure out how to fix every individual commits.

2022-01-12 00:10 UTC, JessicaGreben commented
@fishy I was assuming we would squash everything. But if we prefer individual commits, then I need to fix this. Let me know @fishy/@kylelemons .

2022-01-12 00:12 UTC, fishy commented
We went thought the rebase before so that we could still keep the individual commits in the end 😅 

But I'm also not against just squash a single commit in the end ¯\\\_(ツ)\_/¯

2022-01-12 00:24 UTC, kylelemons commented
Recommended merge strategy:
* Combine the last ones (that don't ahve a PR number) into one commit, say titled "Final polish for merge into master (#467)"
* and then rebase-and-merge.

This keeps the work units nicely separated, keeps links to the original PRs, etc

2022-01-12 00:54 UTC, closed without merging