Adjust default client middleware order to handle retries
reddit/baseplate.go pull request #474
Opened 2022-01-26 20:00 UTC by fishy

For thriftbp, we used to use two MonitorClient middlewares, one before
and one after Retry, to record both raw and -with-retry metrics, so do
the same thing for PrometheusClientMiddleware.

For httpbp, move PrometheusClientMetrics to before Retries so it records
the metrics with retries, same as how MonitorClient middleware is doing
today.

2022-01-27 19:54 UTC, kylelemons requested changes
hmm.  Are we sure we want this? This means that I can't tell how many _actual_ requests are being sent (QPS wise)

2022-01-27 20:01 UTC, fishy commented
> hmm. Are we sure we want this? This means that I can't tell how many _actual_ requests are being sent (QPS wise)

For thrift we report both with different slug tags (slug and slug-with-retry), with the one without retry is the raw QPS.

For http, I'm just matching the current behavior of `MonitorClient` in the default middlewares. I'm not sure what was the reason to only report with-retry metrics but not the raw ones. cc @konradreiche who originally added the default http client middlewares.

2022-01-28 00:06 UTC, JessicaGreben approved these changes
I have a slight preference of httpbp and thriftbp Prom Middleware both tracking before and after retries. But if this PR matches past behavior, then I can be convinced this is fine the way it is.

2022-01-31 17:45 UTC, konradreiche approved these changes
This looks correct to me, before the addition of Prometheus client metrics retries was executed last too.

2022-01-31 18:01 UTC, fishy commented
:haircut: Added both -with-retry raw metrics for httpbp clients.

cc @konradreiche this will change the behavior of your dashboards, basically what client side metrics you get now for `client="foo"`, you need to use `client="foo-with-retry"` instead to get the same metrics (the `client="foo"` metrics are now raw metrics).

2022-01-31 18:14 UTC, konradreiche approved these changes

2022-01-31 18:26 UTC, kylelemons approved these changes

2022-01-31 18:59 UTC, merged