bug fix for reading thrift headers
reddit/baseplate.go pull request #500
Opened 2022-03-30 16:17 UTC by marcoferrer

This is a fix to bring baseplate go in sync with baseplate py.

2022-03-30 16:51 UTC, fishy requested changes

2022-03-30 16:51 UTC, fishy commented on thriftbp/headers.go
> +func Header(ctx context.Context, key string) (v string, ok bool) {
I don't think we want to export this. if a service code need to do the same thing they can just duplicate this function.

2022-03-30 16:51 UTC, fishy commented on thriftbp/headers.go
> +		v, ok = thrift.GetHeader(ctx, strings.ToLower(key))
if you are certain that what envoy does is just lowercase the key, then this is enough and we won't need option 2.

2022-03-30 17:05 UTC, fishy reviewed
the code lgtm, but before we can merge it:

1. The PR title should be something like "Workaround a bug in envoy" as this is not a bug in baseplate.go
2. We need to file a bug on envoy, and link the bug here, so we could revert this change in the future when the bug is fixed in envoy.

2022-03-30 17:05 UTC, fishy commented on thriftbp/headers.go
> +// If the value is not present we fall back to a case-insensitive check
s/fall back to a case-insensitive check/fall back to all lowercase check to workaround a bug in envoy/

2022-03-30 17:22 UTC, fishy commented
https://github.com/envoyproxy/envoy/issues/20595

2022-03-30 17:48 UTC, kylelemons requested changes

2022-03-30 17:48 UTC, kylelemons commented on thriftbp/headers.go
> +		// We fall back to a case-insensitive check so that we can have
This is incorrect -- it's not a case-insensitive check, it's a lower-case check.

I think you should say
```
We fall back to checking the key that an envoy proxy will send, which is a lower-case
version of the thrift key.

For details on this workaround, see:
* <link to this PR or whatever>
* <link to the envoyproxy/envoy bug>
```

2022-03-30 19:43 UTC, marcoferrer commented on thriftbp/headers.go
> +		// functional parity with baseplate-py
```suggestion
		// We fall back to checking the key that an envoy proxy will send, which is a lower-case
		// version of the thrift key.
		// 
		// 
		// For details on this workaround, see:
		// 	* https://github.com/reddit/baseplate.py/blob/0d189bae9bc15459b8d9d62856f31e45cbfcdb1a/baseplate/frameworks/thrift/__init__.py#L111	
		// 	* https://github.com/envoyproxy/envoy/issues/20595
		// 	* https://github.com/reddit/baseplate.go/pull/500
```

2022-03-30 19:47 UTC, marcoferrer commented on thriftbp/headers.go
> +		// 	* https://github.com/reddit/baseplate.py/blob/0d189bae9bc15459b8d9d62856f31e45cbfcdb1a/baseplate/frameworks/thrift/__init__.py#L111
```suggestion
		// 	* https://github.com/reddit/baseplate.py/commit/daf1c5e32dcc019470d75f3940006bb2f7b9855e	
```

2022-03-31 16:55 UTC, marcoferrer commented on thriftbp/headers.go
> +// If the value is not present we fall back to a case-insensitive check
```suggestion
// If the value is not present we fall back to all lowercase check to workaround a bug in envoy
```

2022-03-31 17:05 UTC, fishy approved these changes

2022-03-31 17:49 UTC, kylelemons approved these changes

2022-03-31 17:56 UTC, pacejackson approved these changes

2022-03-31 20:33 UTC, fishy commented
you have extra trailing spaces: https://github.com/reddit/baseplate.go/runs/5775116141?check_suite_focus=true

2022-04-04 22:40 UTC, merged