Use strconv.FormatBool
reddit/baseplate.go pull request #512
Opened 2022-04-20 07:49 UTC by SuperQ

Remove reimplementaiton of stdlib function strconv.FormatBool().

Signed-off-by: SuperQ <superq@gmail.com>

2022-04-20 15:37 UTC, fishy requested changes

2022-04-20 20:16 UTC, konradreiche requested changes
Can we instead mark it as deprecated?

2022-04-21 12:21 UTC, konradreiche approved these changes

2022-04-21 16:04 UTC, fishy requested changes
The commit message of 9ad9f79d34867828c720a48b6c8a01aa283867b7 explained why we added this, marking it as deprecated does not resolve the problem.

We can probably mark it as deprecated when we mark the whole `metricsbp` package as deprecated, and even that is still debatable. But we certainly should not mark it as deprecated now.

2022-04-21 17:42 UTC, kylelemons requested changes
I'm with @fishy I think.

We can deprecate this function when we deprecate metricsbp, and we can use a source rewrite to remove it from call-sites.  (I would replace it with a string, not the call to strconv, when it's a literal `true` or `false` as well.)

2022-04-22 06:20 UTC, closed without merging