Set a max CPU scale multiplier
reddit/baseplate.go pull request #597
Opened 2023-01-30 15:08 UTC by SuperQ

## 💸 TL;DR
In order to avoid users mixing up `BASEPLATE_CPU_REQUEST_SCALE` and `BASEPLATE_CPU_REQUEST`, set a maximum scaling factor to 3.

## 📜 Details
[Design Doc]()

[Jira]()

## 🧪 Testing Steps / Validation

## ✅ Checks

- [ ] CI tests (if present) are passing
- [ ] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

2023-01-30 15:09 UTC, SuperQ commented
I thought about a few other options:
* Crash if the scale is too high.
* Set back to default if scale is too high.

I was also thinking about adding a max check to see if request*scale > runtime.NumCPU(). Would need some mocks to make testing easier.

2023-01-30 16:56 UTC, mterwill reviewed
Is this really necessary? Setting GOMAXPROCS too high will have performance but not safety implications for a given application. There are logs + metrics around all of this; should be easy enough for a service owner to detect and correct a misconfiguration, especially as they're validating their change.

2023-01-30 16:59 UTC, SuperQ commented
The reason we found this was due to a service configuring the scale multiplier to 20 with a request of 10. This created 200 runable threads on a 96 cpu instance. Not only is this impacting the service, the number of threads was impacting other containers on the same system in a very negative way.

2023-01-30 17:09 UTC, fishy commented
> The reason we found this was due to a service configuring the scale multiplier to 20 with a request of 10. This created 200 runable threads on a 96 cpu instance. Not only is this impacting the service, the number of threads was impacting other containers on the same system in a very negative way.

But that's just a misconfiguration. Someone can also misconfigure request to 200 which will achieve the same thing. I don't think a subtle arbitrary limitation is a good way to handle misconfigurations.

2023-01-30 17:10 UTC, mterwill commented
Agree. If we're really concerned about this we could check in infrared and fail to render the manifest.

2023-01-30 18:28 UTC, SuperQ commented
What about a check to make sure `GOMAXPROCS` is never more than `runtime.NumCPU()`?

2023-01-30 18:37 UTC, fishy requested changes
> What about a check to make sure `GOMAXPROCS` is never more than `runtime.NumCPU()`?

`runtime.NumCPU()` is out of developers' control (they have no control on which node the pod will be scheduled on, it could be anything between 4 cpu or 128 cpu node), so this will introduce random failures on deploys.

2023-01-30 19:05 UTC, SuperQ commented
Yes, that's what I'm saying. We can clamp things to the `runtime.NumCPU()`. It's not going to cause a failure, it's just going to avoid spinning up 200 threads on a 4 CPU node.

2023-01-30 19:42 UTC, fishy commented
that goes back to my original point that the same pod deployed to different nodes will have different performance (for example, for services requesting 4*2, will have NumCPU capped at 4 when it's deployed to a small node, but have the full 8 when it's deployed to a bigger node).

2023-01-30 21:44 UTC, kylelemons commented
The default for GOMAXPROCS, if memory serves, was 2*CPUs+1 for a long time,
so I'm not sure that the CPU count makes sense either as an upper bound.

I think this is something that should be detected and addressed at a
different layer, maybe monitoring, and ideally based on whatever metric is
correlated with the performance loss (CPU contention? Context switches?),
since this is only one way we can hit such cases.

On Tue, Jan 31, 2023, 3:28 AM Ben Kochie ***@***.***> wrote:

> What about a check to make sure GOMAXPROCS is never more than
> runtime.NumCPU()?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/reddit/baseplate.go/pull/597#issuecomment-1409114586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACOVJNJFBMJ23A6WXCLBKLWVAB43ANCNFSM6AAAAAAULIQGCA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-01-30 22:25 UTC, SuperQ commented
@kylelemons From my looking at `runtime/os_linux.go`, it hasn't changed since at least 2014 (when it was converted from C to Go).

We added sched latency metrics, which will be available once v0.9.12 is released. That should give us a good idea if we're running into contention there.

I'm fine closing this, and leaving it for other layers to address. But I still think we should consider having GOMAXPROCS limited to NumCPU. From what I've seen, the go scheduler is not tuned or going to operate sanely with more POSIX threads to run on than real CPUs available to a process.

2023-02-07 17:02 UTC, asandoval commented
Reopening per internal conversations. Consensus is mounting that there are effectively few, if any, practical scenarios where tuning outside of this guidance is advised.

2023-02-07 17:03 UTC, SuperQ commented
I am thinking about changing this proposal to remove the `BASEPLATE_CPU_REQUEST_SCALE` multiplier. If users need an escape hatch, they can directly set `GOMAXPROCS`.

2023-02-07 23:31 UTC, mterwill requested changes
The scale parameter facilitates tuning GOMAXPROCS when used with a vertical pod autoscaler.

2023-02-08 09:42 UTC, SuperQ commented
Yes, and we don't want users to touch the scale value, as they don't know what to do with it. It's not something we want to allow tuning of.

2023-02-08 14:08 UTC, kylelemons commented
We have customers who require this already, and who do know what to do with
it.

On Wed, Feb 8, 2023, 6:42 PM Ben Kochie ***@***.***> wrote:

> Yes, and we don't want users to touch the scale value, as they don't know
> what to do with it. It's not something we want to allow tuning of.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/reddit/baseplate.go/pull/597#issuecomment-1422310297>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACOVJLZ4FLLNOQZVLRI5QDWWNTAVANCNFSM6AAAAAAULIQGCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-14 20:26 UTC, BigValen commented
Could we make it harder to misinterpret ? Like support keywords, like { HIGH_IO=2.5, DEFAULT=2, CPU_INTENSIVE=1.5 } or something ? Bounds checking ?

2023-02-14 21:05 UTC, kylelemons commented
This has exceeded the discussion that can be reasonably conducted as part of a pull request.

If you want to proceed with a change here, please create a decision doc to gather input and establish consensus, and create a meeting if we can't come to one.

2023-02-14 21:05 UTC, closed without merging